# Template for API configuration
# Copy this file to config.secrets.yaml and fill in your actual API keys

llm:
  provider: openrouter  # or openai
  api_key: your_api_key_here
  # Optional settings
  model: mistral-7b-instruct  # Default model to use
  temperature: 0.7
  max_tokens: 1000
  # Base URL (if needed)
  api_base: https://openrouter.ai/api/v1
