# Configuration Template for Telecom Dashboard
# Copy this file to config.secrets.yaml and fill in your actual values

# LLM Configuration for AI Insights
llm:
  provider: "openrouter"  # Using OpenRouter for access to multiple models
  api_key: "your-openrouter-api-key-here"  # Get from https://openrouter.ai/
  model: "openai/gpt-4-1106-preview"  # GPT-4.1 Turbo for best performance
  temperature: 0.7  # Balanced creativity and consistency
  max_tokens: 1000  # Sufficient for detailed insights
  api_base: "https://openrouter.ai/api/v1"  # OpenRouter API endpoint

# Database Configuration
database:
  path: "data/telecom_db.sqlite"
  backup_enabled: true
  backup_interval_hours: 24

# Theme Configuration
theme:
  default: "cognizant"
  available_themes: ["cognizant", "verizon"]
  auto_switch: false

# Feature Flags
features:
  ai_insights: true
  benchmark_management: true
  data_export: true
  real_time_updates: false
